server:
  port: ${SERVER_PORT:9090}

spring:
  application:
    name:  ${APPLICATION_NAME:restaurant-service}
  datasource:
    url: jdbc:mysql://${MYSQL_SERVICE:localhost}:3306/restaurants?createDatabaseIfNotExist=true
    username: root
    password: ${MYSQL_ROOT_PASSWORD:moopi}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    register-with-eureka: ${REGISTER_WITH_EUREKA:true}
    service-url:
      defaultZone: ${DEFAULT_ZONE:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true